import type { Metadata } from "next";
import "./globals.css";
import { Auth } from '@/components/elements/auth'
import { Toaster } from '@/components/ui/sonner'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <header>
          <Auth />
        </header>
        <main>
          {children}
        </main>
        <footer>

        </footer>
        <Toaster />
      </body>
    </html>
  );
}
